console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true
enable_cursor_positioning = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'cyan'
    background = 'transparent'
    template = '<b>{{ .Path }}</b>'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#6c6c6c'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'magenta'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = '5000'
      style = 'round'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}yellow{{end}}",
    ]
    background = 'transparent'
    template = '<f>❯</f>'

[transient_prompt]
foreground = 'yellow'
background = 'transparent'
template = '❯ '

[secondary_prompt]
  foreground = 'yellow'
  background = 'transparent'
  template = '❯❯ '

[palette]
mint = '#4e9a06'

